### ISSUE TITLE
Private Messaging - Player Not Online

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#10]
Fix issue with /msg /tell showing player not online while they ARE online.
/r seems to work fine after first msg is sent.

Shows "This player is not online or doesn't exist!" multiple times.

**Comment by Deathinflames** [comment]
This is a cross server issue, the plugin is attempting to locate the player to send the message to on the same server as the origin of the message, but because the player is on a different server it returns that message. 

I have yet to see a message fail when typing out the player name and using /tell(/r then becomes available). Are you advising that this message will occur anyway when that is done?
 
In any case, the developer is aware of this issue however a fix has yet to be released.

**Comment by Fyreheart** [comment]
Okay! 
When I attempt to use "/tell" to message a player on any server, it gives me a DoD Help section on /tell and /chat as seen in the picture instead of sending a message. This happens whether I am on the same server as the player or not.

![image](https://user-images.githubusercontent.com/42979450/45119077-5b196800-b128-11e8-8223-76d994f555c5.png)

**Comment by Deathinflames** [comment]
This issue has been resolved.
