### ISSUE TITLE
USB - Tamed Wolves

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#2]
Grown tamed dogs do not attack.

**Comment by Deathinflames** [comment]
Has this been tested to see if it is still occurring after the server was updated to 1.12.2?

**Comment by Fyreheart** [comment]
I just tested it. When I attack a mob, my tamed wolf does not attack.

**Comment by Deathinflames** [comment]
After self-testing this feature, it does in fact appear to be working as intended.

So in order to make this work, you need to use the mcMMO skill "Call of the Wild" which of course requires 10 bones to summon a tamed wolf. According to the code, this should work for any wolf that are owned by the player however this may not always be the case but it will always work for freshly summoned wolves until for whatever reason the internal owner that is attached to that wolf is either changed or lost.

Once the wolf is summoned, each time you attack a hostile mob a check is made, the check looks for any hostile mobs within 40 yards of the player and if there are any hostiles the wolf will automatically attack those targets.
