### ISSUE TITLE
ESB - Custom Enchant: Rage

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#38]
Attacking/Left clicking with a sword with Rage enchant gives an error:

Condition (%attackercombo%>5) contains letters, but must be numeric only.

![unonescreen](https://user-images.githubusercontent.com/42979450/60544609-22660300-9ce7-11e9-812f-9620c16cdd8f.png)

**Comment by Deathinflames** [comment]
After further investigation of this issue, it appears that combo only pertains to PvP combat and therefore will require the entire enchant to be replaced. The enchant may return at a later time.

The enchant has been replaced with Berserk
![d5736106ee7f4086b1e6e0432d1d8860](https://user-images.githubusercontent.com/6750890/60549439-13308680-9ce2-11e9-8aa4-f3f70f87e250.png)

If you have an item already enchanted with this enchant, or if you have a rage enchanted book, please notify a staff member so that it can be replaced with an Uncommon Ancient Tome.
