### ISSUE TITLE
ESB - Items Shop consistency issues

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#40]
Some prices of items are different in different categories of the Items Shop. Some for buy and sell, some you can't sell in other places.
Not sure if you want to go back and make the pricing and ability to sell consistent across the different shop categories, or remove from one category.

Poppy. 
Mob Drops, Buy 16 for $300, Sell 16 for $24. 
Decoration, Buy 16 for $800, can't Sell.

Cocoa. 
Farm/Food, Buy 16 for $750, Sell 16 for $46. 
Decoration, Buy 32 for $750, can't Sell.

Ink Sac. 
Mob Drops, Sell 8 for $35. 
Decoration, can't Sell. Buy prices are the same in both, so that's fine.

Lapis. 
Ores, Buy 16 for $750, Sell 16 for $75. 
Decoration, Buy 32 for $750, can't Sell.

Gold. 
Buy 9 Nuggets for $100 in Mob Drops, 
Buy 1 Gold Ingot for $150 in Ores.

Iron Ingot. 
Ores, Buy 1 for $100. 
Mob Drops, Buy 16 for $1200. Sell prices are the same in both, so that's fine.

(Edited to space out for easier reading)

**Comment by Deathinflames** [comment]
This was done for the sake of convenience. If you notice, the items that are sellable are located in categories that would be the most common way that players would receive those items so therefore it was made possible to sell those items in the corresponding common categories from which those items were most likely obtained.

If this causes too much confusion, i'm happy to remove these changes and only make them sellable in their appropriate locations, ie: poppies -> flowers/decorations ONLY instead of mob drops(golems) AND flowers/decorations. Using this example as a reference, if a player has poppies to sell to the store, they more than likely received them from a iron golem spawner rather than over purchasing poppies from the flower/decorations category and so the player is most likely emptying their chest of Mob Drops rather than their flower chest and because they are already in the Mob Drops area....they can simply click their other mob drops to sell to the server easily, etc etc.

**Comment by Fyreheart** [comment]
I'm fine with the items being in different categories as it can be easier for players to find, but the main issue in my opinion is there are different prices in different places for the same exact item and quantity.

For example, if I went in the /shop to buy Cocoa, and I buy 16 for $750 from the Farm/Food section, then see I could have gotten 32 instead for the same price in the Decoration section, I've wasted some money.
You can also sell them to Farm/Food shop, but cannot sell them to the Decoration shop.

Thankfully, nothing is expensive enough to be a huge difference.. I think it would be better to have the same prices and same ability to buy/sell no matter where you find it in the shop.

**Comment by Deathinflames** [comment]
Just putting this here to remind myself. :) Add more "back" buttons in the /shops.

**Comment by Deathinflames** [comment]
Fixed the discrepancies in the shops. Also added more "back" buttons.
