### ISSUE TITLE
Discord - Livechat, Joined Survival

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#42]
Livechat does not post when someone connects to the Survival server.

It should say:
[SV] Playername has joined the server.

**Comment by Deathinflames** [comment]
![612a33443111205336c29107ebb518af](https://user-images.githubusercontent.com/6750890/60826356-e14c7380-a16a-11e9-817e-5d8ceaf1fa26.png)

I have not touched anything since this was reported and according to discord livechat, It does appear to be functioning properly. Now, it is important to note the difference between joining the network for the first time and joining a server on the network for the first time. It will NOT notify in livechat when a player that has never joined a server on the network because ofc they do not yet have the permission for that until their player files are created by the server. After this point, it will then start to notify when a player joins/leaves.

Currently, only the hub is set to notify in livechat that they are joining for the network for the first time and no other server on the network should be doing this except the hub server.

**Comment by Deathinflames** [comment]
Since it's just the first join for a new player that's being affected for individual servers on the network, i'm going to add a on join event for the first join for each server so that it "appears" like a normal join from a brand new player but is actually a first join where the initial permission is being missed. I know that sounds extremely confusing but, trust me. :)
