### ISSUE TITLE
ESB - Additional Command Aliases

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#58]
Have "/is invite (player)" either do the proper command or message the player to use "/is team invite (name)"

Have "/is upgrades" do "/isupgradegui"

**Comment by Deathinflames** [comment]
Due to how BSkyBlock was developed, and the current views of those developers, any custom arguments or modification to existing arguments after the command "/is" will require a dedicated addon or direct modification to the source code. 

Unfortunately, It just isn't worth the time and effort at this time to create this functionality however there is still a chance this will be developed via custom functionality in the future.

As for the upgrade GUI aliases, I've added the "/upgrade" command that will be the main shortcut to the island upgrade GUI.
