### ISSUE TITLE
Parkour - Issues and Concerns

### ISSUE THREAD

**Issue by Fyreheart** [Deathinflames/DoD#79]
Hovering over the Head block in slot 9 in the hotbar shows 0 for all stats. Incorrect.

Is it possible for players to only have 1 score per course? Instead of 1 player getting all 3 top spots.

You don't "die"/get sent back to checkpoint when you fall in the Diamond course. Set those leaf blocks as the death blocks for that course, or put a layer of Barrier above them and have Barrier be the death block?

House parkour, two wood blocks used to be water source blocks. Change back?
![houseparkourwater](https://user-images.githubusercontent.com/42979450/68791269-efc60280-0616-11ea-906d-a31210ca3fff.png)

Trigger had suggested rewards for beating records. That would be easily exploitable, but I have an alternative suggestion:  Default records to aim for for each course, like standard records to beat. and if you get the record or better you get a one time 5 bonus tokens for that course.

Change the Parkour Warps block to an item instead of a full block, to prevent block glitching.

Add a button to "restart" the course instead of a player having to leave the course and re-join it, for those trying to get highscores on the leaderboards.

Player Report: "On the map "Zen" there  are mossy cobblestone blocks used in the building which have the unintended effect of a massive jump boost."

**Comment by Deathinflames** [comment]
> Hovering over the Head block in slot 9 in the hotbar shows 0 for all stats. Incorrect.

This has been updated.


> Is it possible for players to only have 1 score per course? Instead of 1 player getting all 3 top spots.

Unfortunately, at the present moment this is not possible. It has been suggested to the developer that this feature be added and will be updated ASAP if the developer decides to implement this feature.


> You don't "die"/get sent back to checkpoint when you fall in the Diamond course. Set those leaf blocks as the death blocks for that course, or put a layer of Barrier above them and have Barrier be the death block?

The Diamond course now has faster death blocks.

> House parkour, two wood blocks used to be water source blocks. Change back?

These two blocks have been changed back to water source blocks.

> Trigger had suggested rewards for beating records. That would be easily exploitable, but I have an alternative suggestion: Default records to aim for for each course, like standard records to beat. and if you get the record or better you get a one time 5 bonus tokens for that course.

This is a really good suggestion. I would need feedback for the recommended "standard records" to beat for all current courses in order to implement this, but it is definitely possible.

> Change the Parkour Warps block to an item instead of a full block, to prevent block glitching.

The Parkour Warps block is now an Arrow item.

> Add a button to "restart" the course instead of a player having to leave the course and re-join it, for those trying to get highscores on the leaderboards.

A slimeball item will now appear on the hotbar after joining a course that will allow a player to restart their current course.

> Player Report: "On the map "Zen" there are mossy cobblestone blocks used in the building which have the unintended effect of a massive jump boost."

Great catch, this was due to the course not being properly linked to its corresponding set of special parkour blocks and is now updated.
