### ISSUE TITLE
ESB - Mending isn't working on my account

### ISSUE THREAD

**Issue by LupoSan** [Deathinflames/DoD#82]
**Describe the bug**
I have mending on a pickaxe, sword, diamond chestplate and diamond boots but They are all at various levels of injury and not healing even thought the armor pieces have seen days of no action, the sword has seen at least days of no action and the pickaxe gets rarely used with plenty of time to heal but never does.

**To Reproduce**
1. Equip mentioned item
2. Note current health level
3. Use item
4. Note decrease in item health
5. Stand around or go do something else for several minutes.
6. Note that the items are not healing despite having mending on them.

**Expected behavior**
Items should be mending/healing.

**Screenshots**
![20191218_080735](https://user-images.githubusercontent.com/35648628/71092944-d06a4a00-216d-11ea-8071-28468a06e54e.jpg)

**Minecraft Version:**
 - Version [e.g. 1.13.2]

**Comment by Deathinflames** [comment]
I don't think this is an actual server/game issue but rather a misunderstanding about how mending works internally.

According to [https://minecraft.gamepedia.com/Mending](https://minecraft.gamepedia.com/Mending)

> When an item with the enchantment is held or equipped (in the main hand, offhand, or armor slots), collected experience orbs repair the item at a rate of 2 durability per XP instead of adding the XP to the player's total experience. If multiple items have the enchantment, one is chosen at random for each XP orb collected, and if the chosen item does not need repair, the XP is added to the player's total as normal, rather than choosing another item to repair. 

This is the important part:
**If multiple items have the enchantment, one is chosen at random for each XP orb collected**

This is also saying that if you're wearing 4 pieces of armor with mending, it will take 4x as long because of one being chosen at random. If you really want to test if mending is working properly or not, take all your armor off except one piece and then spam experience bottles, it should repair properly.

Now, if you want durability to restore automatically without doing anything(unbreakable), then you'll need to obtain the custom enchant called "Reforged".
